### ISSUE TITLE
Придумать способ хранения реестров внутри фонда

### ISSUE THREAD

**Issue by chebykin** [andromedaspace/galtproject-docs#40]

**Comment by chebykin** [comment]
У нас будет несколько реестов различных сущностей. Как на локальном, так и на глобальном уровне.

Локальный пример - реестр заявок делегатов.
Глобальный пример - реестр дао.

Необходимо придумать способ хранения подобных реестров с учетом возможности обновления контрактов.

**Comment by chebykin** [comment]
Стоит изучить применимость подхода https://github.com/zeppelinos/zos-lib

**Comment by chebykin** [comment]
Займет несколько дней. Я подберу и опубликую здесь возможные варианты.

**Comment by litvintech** [comment]
One more option for research
https://github.com/Thetta/Thetta-DAO-Framework

**Comment by chebykin** [comment]
Были изучены следующие паттерны обновления через proxy:
## Eternal storage - отдельный контракт играет роль key/value хранилища 

https://github.com/zeppelinos/labs/tree/master/upgradeability_using_eternal_storage

плюсы
- отсутсвует проблема перезаписи адреса контракта логики

минусы
- очень сложная структура хранения key/value

## Unstructured storage - адрес контракта логики прописывается в практически рандомном индексе хранилища (storage) 

https://github.com/zeppelinos/labs/tree/master/upgradeability_using_unstructured_storage

плюсы
- используются нативные типы данных, а не mapping-и
- мы можем быстро отказаться от upgradability с минимальной модификацией кода

минусы
- все еще существует вероятность перезаписать адрес конктракта логики, но она минимальна. Для этого необходимо подобрать keccak256 хеш, что выглядит мало реализуемо.

Пока останавливаемся на варианте UnstructuredStorage.

---
References
* https://blog.zeppelinos.org/proxy-patterns/
* https://blog.indorse.io/ethereum-upgradeable-smart-contract-strategies-456350d0557c
* https://blog.zeppelin.solutions/proxy-libraries-in-solidity-79fbe4b970fd
* https://blog.aragon.one/advanced-solidity-code-deployment-techniques-dc032665f434
