### ISSUE TITLE
Описать, в каких случаях Space токены могут находиться на мультисиги

### ISSUE THREAD

**Issue by chebykin** [andromedaspace/galtproject-docs#50]
Как учитывается репутация в таких случаях?

**Comment by Jonybang** [comment]
я думаю только в одном случае:
Когда пользователь отказывается от земли в пользу фонда - фонд получает эту землю в собственность и может выложить её на аукцион или распорядится землей иначе

**Comment by Jonybang** [comment]
Или когда кто-то просто передает фонду землю

**Comment by Jonybang** [comment]
Ещё может быть такой кейс когда мультисиг участвует в аукционе земли как тот кто делает ставку?

**Comment by chebykin** [comment]
мультисиг исключен из функционала обратного выкупа space токенов, поэтому никаких особенностей владения space-токенами у мультисигов нет
