### ISSUE TITLE
Вопросы по Reputation, которые нужно описать в документации

### ISSUE THREAD

**Issue by Jonybang** [andromedaspace/galtproject-docs#76]
- При передачи токена от одного владельцу к другому: каким образом новый владелец может получить себе репутацию токена?
- Какие действия новый владелец токена может выполнять с репутацией токена до того как сделает revoke?(Волнует безопасность)
- Можно ли распределять сданную в аренду пользователю репутацию между другими пользователями?
- Что за периоды аренды в Примере 3, как они работают, на что влияют?
- Чем отличается контракт совместной аренды от сдачи репутации в аренду другим пользователям? Какие правила прописаны в контракте совместной аренды, которые дают арендатору какие-то гарантии в отличии от сдачи репутации в аренду другим пользователям?

**Comment by chebykin** [comment]
1. описано в https://github.com/andromedaspace/galtproject-docs/blob/master/ru/contracts/Reputation.md#%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80-0-%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C-%D0%B5%D0%B4%D0%B8%D0%BD%D0%BE%D0%BB%D0%B8%D1%87%D0%BD%D0%BE-%D0%B2%D0%BB%D0%B0%D0%B4%D0%B5%D0%B5%D1%82-%D0%97%D0%B5%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC-%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%BA%D0%BE%D0%BC-%D0%B8-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D0%B5%D1%82-%D0%B5%D0%B3%D0%BE-%D0%B4%D1%80%D1%83%D0%B3%D0%BE%D0%BC%D1%83-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8E

2. не понял вопроса. 
3 и 4 и 5. аренда не является функционалом контракта репутации; периоды аренды не являются функционалом репутации, приведены для примера. будут описаны в доке по стороннему контракту аренды
